docker-worker:
  workerImplementation: docker-worker
  gcp:
    image: projects/taskcluster-imaging/global/images/docker-worker-gcp-googlecompute-2019-11-04t22-31-35z

generic-worker-win2012r2:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-04ff4e4c220abce54
      us-west-1: ami-070ee00d395f493d3
      us-west-2: ami-02161407768d981ea
  gcp:
    image: projects/pmoore-dev/global/images/win2012r2-rzuhq8vonqvbsgvhdqsd
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        livelogExecutable: C:\generic-worker\livelog.exe
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/generic-worker/2509a1f8589b0b536186f5fe8f043385bf67197f/worker_types/win2012r2/bootstrap.ps1

generic-worker-win2012r2-staging:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-04ff4e4c220abce54
      us-west-1: ami-070ee00d395f493d3
      us-west-2: ami-02161407768d981ea
  gcp:
    image: projects/pmoore-dev/global/images/win2012r2-rzuhq8vonqvbsgvhdqsd
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        livelogExecutable: C:\generic-worker\livelog.exe
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/generic-worker/2509a1f8589b0b536186f5fe8f043385bf67197f/worker_types/win2012r2/bootstrap.ps1

generic-worker-ubuntu-18-04:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-00477f6d6e091167d
      us-west-1: ami-004d920c923ee252d
      us-west-2: ami-0cbc5f32c8bbb1ec9
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        livelogExecutable: /usr/local/bin/livelog
        taskclusterProxyExecutable: /usr/local/bin/taskcluster-proxy
        tasksDir: /home
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/generic-worker/ba5c21e60957f5ed3395f848f975a7ae8b147252/worker_types/gwci-linux/bootstrap.sh

generic-worker-ubuntu-18-04-staging:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-029a1539ae3ce69b0
      us-west-1: ami-047fd83611b397644
      us-west-2: ami-056c7a4b568d09255
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        livelogExecutable: /usr/local/bin/livelog
        taskclusterProxyExecutable: /usr/local/bin/taskcluster-proxy
        tasksDir: /home
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/generic-worker/ba5c21e60957f5ed3395f848f975a7ae8b147252/worker_types/gwci-linux-beta/bootstrap.sh

deepspeech-win2012r2:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-00ac6736f325c15b8
      us-west-1: ami-000f332719212504f
      us-west-2: ami-032a6d4f0021ad2a9
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        livelogExecutable: C:\generic-worker\livelog.exe
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        workerTypeMetadata:
          machine-setup:
            maintainer: alissy@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/generic-worker/2509a1f8589b0b536186f5fe8f043385bf67197f/worker_types/deepspeech-win/bootstrap.ps1
